name = "d1-example"
main = "src/worker.js"
compatibility_date = "2024-10-18"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
head_sampling_rate = 1

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "d1-example"
database_id = "00194bf7-cd50-4dfd-810b-21b12381e177"

routes = [
  { pattern = "d1.rogercorreia.xyz/*", zone_name = "rogercorreia.xyz" }
]